# Generated by Django 3.2 on 2021-12-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=100, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, upload_to='agents', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la propriété')),
                ('prix_vente', models.IntegerField(blank=True, null=True, verbose_name='Prix de vente')),
                ('prix_location', models.IntegerField(blank=True, null=True, verbose_name='Prix de location')),
                ('enVente', models.BooleanField(default=True, verbose_name='En vente')),
                ('enLocation', models.BooleanField(default=True, verbose_name='En location')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, default='non disponible', max_length=100, verbose_name='Code postal')),
                ('superficie', models.IntegerField(blank=True, default=0, verbose_name='Superficie')),
                ('nb_pieces', models.IntegerField(blank=True, default=0, verbose_name='Nombre de pièces')),
                ('nb_chambres', models.IntegerField(blank=True, default=0, verbose_name='Nombre de chambres')),
                ('nb_salles_de_bain', models.IntegerField(blank=True, default=0, verbose_name='Nombre de salles de bain')),
                ('nb_salles_de_douche', models.IntegerField(blank=True, default=0, verbose_name='Nombre de salles de douche')),
                ('nb_toilettes', models.IntegerField(blank=True, default=0, verbose_name='Nombre de toilettes')),
                ('nb_garages', models.IntegerField(blank=True, default=0, verbose_name='Nombre de garages')),
                ('nb_etages', models.IntegerField(blank=True, default=0, verbose_name="Nombre d'étages")),
                ('nb_balcons', models.IntegerField(blank=True, default=0, verbose_name='Nombre de balcons')),
                ('nb_terrasses', models.IntegerField(blank=True, default=0, verbose_name='Nombre de terrasses')),
                ('galerie', models.ImageField(blank=True, upload_to='images/', verbose_name='Galerie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('video', models.URLField(blank=True, verbose_name='Video')),
            ],
        ),
    ]
