# Generated by Django 3.2 on 2021-12-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='Agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estate.agent', verbose_name='Agent'),
            preserve_default=False,
        ),
    ]
