# Generated by Django 3.2 on 2021-12-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_propriete_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propriete',
            old_name='Agent',
            new_name='agent',
        ),
        migrations.AlterField(
            model_name='propriete',
            name='superficie',
            field=models.IntegerField(blank=True, default=0, help_text='en m²', verbose_name='Superficie'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='video',
            field=models.URLField(blank=True, help_text=' ex : https://www.youtube.com/embed/', verbose_name='Video'),
        ),
        migrations.CreateModel(
            name='Proximite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etablissement', models.CharField(max_length=100, verbose_name='Etablissement')),
                ('distance', models.IntegerField(verbose_name='Distance')),
                ('Propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.propriete', verbose_name='Propriete')),
            ],
        ),
    ]
