# Generated by Django 3.2 on 2021-12-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_auto_20211206_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propriete',
            old_name='galerie',
            new_name='poster',
        ),
    ]
