# Generated by Django 3.2 on 2021-12-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_rename_galerie_propriete_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProprieteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('78be8581-d04a-4919-965f-15a32e2ac6f0', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.propriete', verbose_name='Propriété')),
            ],
        ),
    ]
