# Generated by Django 3.2 on 2021-12-06 17:40

from django.db import migrations, models
import estate.models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_proprieteimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprieteimage',
            name='78be8581-d04a-4919-965f-15a32e2ac6f0',
        ),
        migrations.AddField(
            model_name='proprieteimage',
            name='image',
            field=models.ImageField(default=1, upload_to=estate.models.image_directory, verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, upload_to=estate.models.image_directory, verbose_name='Photo'),
        ),
    ]
