# Generated by Django 3.2.5 on 2021-12-08 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import estate.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate', '0006_auto_20211206_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proprieteimage',
            options={'verbose_name': 'Image de la propriété', 'verbose_name_plural': 'Images de Propriété'},
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/agents/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='poster',
            field=models.ImageField(blank=True, upload_to=estate.models.image_directory, verbose_name='Galerie'),
        ),
    ]
